---
name: "merge-release-hotfix"
# rebuild any PRs and main branch changes
"on":
  pull_request:
    types:
      - closed
    branches:
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  MergeReleaseHotfix:
    if: github.event.pull_request.merged

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Self test
        id: selftest
        uses: ./
        with:
          GithubToken: ${{secrets.GITHUB_TOKEN}}
          SourceRef: ${{github.ref_name}}
          TargetRefs: main
