---
name: Release

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

"on":
    push:
        branches:
            - main
    pull_request:
        types:
            - "labeled"
            - "synchronize"

jobs:
    release:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: ./.github/actions/setup-asdf
              with:
                  SetupCommand: "./setup.bash"

            - uses: ./.github/actions/setup-npm

            - name: Create Release
              env:
                  GIT_AUTHOR_EMAIL: releasebot@github.com
                  GIT_COMMITTER_EMAIL: releasebot@github.com
                  GIT_AUTHOR_NAME: releasebot
                  GIT_COMMITTER_NAME: releasebot
                  GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.RELEASE_BOT_NPM_TOKEN }}
              run: npm run release
