---
name: "build-test"
# rebuild any PRs and main branch changes
"on":
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # make sure build/ci work properly
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-asdf
        with:
          SetupCommand: "./setup.bash"
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run types
      - run: npm run build
      - run: npm run package
      - run: npm run test

  # make sure the action works on a clean machine without building
  SelfTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Self test
        id: selftest
        uses: ./
        with:
          GithubToken: ${{secrets.GITHUB_TOKEN}}
          SourceRef: ${{github.ref_name}}
          TargetRefs: main
