---
name: "build-test"
# rebuild any PRs and main branch changes
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "release/*"

jobs:
  # make sure build/ci work properly
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-asdf
        with:
          SetupCommand: "./setup.bash"
      - uses: ./.github/actions/setup-npm
      - run: npm run lint
      - run: npm run format
      - run: npm run types
      - run: npm run build
      - run: npm run package
      - run: npm run test
