---
name: "build-test"
# rebuild any PRs and main branch changes
"on":
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-asdf
        with:
          SetupCommand: "./setup.bash"
      - run: npm ci
      - run: npm run all
  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GithubToken: ${{secrets.GITHUB_TOKEN}}
          SourceRef: ${{github.ref_name}}
          TargetRefs: main
